[package]
name = "webapp_dioxus"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dioxus-web = "0.4.0"

common = { path = "../common" }
dioxus = "0.4.0"
